public class CallApi {
  //  public Interview__c evnt{get;set;}
    
    public static void call(){
        /*HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse();
        Http http = new Http();
        req.setEndpoint('https://calendar.google.com/calendar?cid=a3VzaGFsYmFnYWRpYS5rcGJAZ21haWwuY29t');
        req.setMethod('GET');
        res = http.send(req);
        system.debug(res);
        if(res.getstatusCode() == 200 && res.getbody() != null){
            system.debug('Response body result is+++: ' + res.getBody());
            List<String> ConsoleWrapperList=(List<String>)json.deserialize(res.getbody(),List<String>.class);
        }*/
        
    //    Interview__c evnt = [Select Id, Date__c, CreatedDate from Interview__c LIMIT 1];
        
                
    }
}